### ISSUE TITLE
import/export

### ISSUE THREAD

**Issue by jaroslaw-weber** [jaroslaw-weber/keyfab#4]
import/export keyboard keys positions, style and other settings

**Comment by jaroslaw-weber** [comment]
done

**Comment by heyzec** [comment]
Hi there, are there future plans to add import and export of key labels?

**Comment by jaroslaw-weber** [comment]
actually yeah it could be nice feature, i just didnt think about it at the time. ill make a new ticket for this but not sure when ill work on this but im open to reviewing merge request.
